export const baseURL ="https://wowfy.in/doutya/api";
export const baseImgURL ="https://wowfy.in/doutya/photos/";
export const baseVidUrl ="https://wowfy.in/doutya/videos/";
// export const baseURL ="http://192.168.1.9/Zen/doutya/api";
// export const baseImgURL ="http://192.168.1.9/Zen/doutya/photos/";
// export const baseVidUrl ="http://192.168.1.9/Zen/doutya/videos/";
// export const baseURL ="http://172.20.10.4/Zen/doutya/api";
// export const baseImgURL ="http://172.20.10.4/Zen/doutya/photos/";
// export const baseVidUrl ="http://172.20.10.4/Zen/doutya/videos/";
